### ISSUE TITLE
Not working on Mac OS

### ISSUE THREAD

**Issue by TobyDS** [kalimahapps/vscode-tailwind-config-viewer#18]
## Description of issue
Hi, at first I received a notification telling me I had to install `@esbuild/darwin-amd64`, which I then did. Now I get a notification that says `The service was stopped` with no other information. I tried looking for more info in the output panel, but there doesn't seem to be one for this plugin specifically. I did however find the following in the Extension Host output.

## Error Log:
```log
2024-12-19 16:10:41.071 [info] ExtensionService#_doActivateExtension KalimahApps.tailwind-config-viewer, startup: false, activationEvent: 'onView:KalimahApps.tailwindcss-config-viewer'
2024-12-19 16:14:11.677 [warning] TextEditor is closed/disposed
2024-12-19 16:14:12.404 [warning] TextEditor is closed/disposed
2024-12-19 16:14:16.806 [warning] TextEditor is closed/disposed
2024-12-19 16:14:19.065 [warning] TextEditor is closed/disposed
2024-12-19 16:14:19.731 [warning] TextEditor is closed/disposed
2024-12-19 16:14:20.376 [warning] TextEditor is closed/disposed
2024-12-19 16:14:21.235 [warning] TextEditor is closed/disposed
2024-12-19 16:14:22.518 [warning] TextEditor is closed/disposed
2024-12-19 16:14:30.273 [info] Extension host terminating: renderer closed the MessagePort
2024-12-19 16:14:30.359 [error] Canceled: Canceled
    at new IT (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:110702)
    at Dy.U (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115312)
    at Proxy.s.<computed>.n.charCodeAt.s.<computed> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112806)
    at cw.g (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32313)
    at cw.executeCommand (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:31817)
    at r.registerCommand.description (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:31147)
    at cw.h (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32833)
    at cw.g (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:31910)
    at cw.executeCommand (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:31817)
    at Object.executeCommand (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:37484)
    at kh.L [as value] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:975601)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.C (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:816)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:1033)
    at Object.p [as dispose] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:997158)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1003280
    at Array.forEach (<anonymous>)
    at b.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1003266)
    at ev.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:109:20047)
    at ev.dispose (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:109:20143)
    at ev.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:978080)
    at ev.dispose (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:109:20143)
    at ai (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:25:699)
    at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:14992
    at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:25:1009
    at Object.dispose (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:8:705)
    at zz.eb (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:11919)
    at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:9874
    at Array.map (<anonymous>)
    at zz.$ (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:9862)
    at zz.terminate (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:10105)
    at QC.terminate (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:1424)
    at Zi (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:15080)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11628)
    at MessagePortMain.emit (node:events:518:28)
    at MessagePortMain.emit (node:domain:489:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949) setContext undefined
2024-12-19 16:14:30.361 [error] Canceled: Canceled
```

## PC Specs:
- Hardware: MacBook Pro M3 Max (apple silicone), 
- Software: Running MacOS Sequoia 15.2.
- Extension Version: 0.0.88
### VSCode Info:
	Version: 1.96.0
	Commit: 138f619c86f1199955d53b4166bef66ef252935c
	Date: 2024-12-11T02:29:09.626Z
	Electron: 32.2.6
	ElectronBuildId: 10629634
	Chromium: 128.0.6613.186
	Node.js: 20.18.1
	V8: 12.8.374.38-electron.0
	OS: Darwin arm64 24.2.0
	
## Other Info
- I was trying to use the extension in a Next.js v15.1 app.
- The following is the contents of my `tailwind.config.ts`:
	```typescript
	import type { Config } from "tailwindcss";
	
	const config: Config = {
		darkMode: ["class"],
		content: [
			"./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
			"./src/components/**/*.{js,ts,jsx,tsx,mdx}",
			"./src/features/**/components/**/*.{js,ts,jsx,tsx,mdx}",
			"./src/app/**/*.{js,ts,jsx,tsx,mdx}",
		],
		theme: {
			extend: {
				backgroundImage: {
					"gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
					"gradient-conic":
						"conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
				},
				borderRadius: {
					lg: "var(--radius)",
					md: "calc(var(--radius) - 2px)",
					sm: "calc(var(--radius) - 4px)",
				},
				colors: {
					background: "hsl(var(--background))",
					foreground: "hsl(var(--foreground))",
					card: {
						DEFAULT: "hsl(var(--card))",
						foreground: "hsl(var(--card-foreground))",
					},
					popover: {
						DEFAULT: "hsl(var(--popover))",
						foreground: "hsl(var(--popover-foreground))",
					},
					primary: {
						DEFAULT: "hsl(var(--primary))",
						foreground: "hsl(var(--primary-foreground))",
					},
					secondary: {
						DEFAULT: "hsl(var(--secondary))",
						foreground: "hsl(var(--secondary-foreground))",
					},
					muted: {
						DEFAULT: "hsl(var(--muted))",
						foreground: "hsl(var(--muted-foreground))",
					},
					accent: {
						DEFAULT: "hsl(var(--accent))",
						foreground: "hsl(var(--accent-foreground))",
					},
					destructive: {
						DEFAULT: "hsl(var(--destructive))",
						foreground: "hsl(var(--destructive-foreground))",
					},
					border: "hsl(var(--border))",
					input: "hsl(var(--input))",
					ring: "hsl(var(--ring))",
					chart: {
						"1": "hsl(var(--chart-1))",
						"2": "hsl(var(--chart-2))",
						"3": "hsl(var(--chart-3))",
						"4": "hsl(var(--chart-4))",
						"5": "hsl(var(--chart-5))",
					},
					sidebar: {
						DEFAULT: "hsl(var(--sidebar-background))",
						foreground: "hsl(var(--sidebar-foreground))",
						primary: "hsl(var(--sidebar-primary))",
						"primary-foreground": "hsl(var(--sidebar-primary-foreground))",
						accent: "hsl(var(--sidebar-accent))",
						"accent-foreground": "hsl(var(--sidebar-accent-foreground))",
						border: "hsl(var(--sidebar-border))",
						ring: "hsl(var(--sidebar-ring))",
					},
				},
			},
		},
		plugins: [require("tailwindcss-animate")],
	};
	export default config;
	```

**Comment by chrisesler** [comment]
same issue

**Comment by abdul-alhasany** [comment]
The exetension uses the installed modules in the project you are working on. I would suggest:
1- Remove node_modules and re-install.
2- Comment out tailwind plugins. This line `plugins: [require("tailwindcss-animate")],`

You can also check these issues they might be able to provide some insight or solution:
- https://github.com/vercel/turborepo/issues/1769
- https://github.com/pnpm/pnpm/issues/5350
- https://github.com/evanw/esbuild/issues/1819#issuecomment-2426254293
